### ISSUE TITLE
docker-compose exemple

### ISSUE THREAD

**Issue by bbmh23** [eric-b/livebox-exporter#3]
Good evening Eric ! 
I have just a small request => can you illustrate an exemple of a docker-compose file in order to demonstrate how can we configure the environment variables "Host" and "Password" please ?
Have a nice evening !
Thank you

**Comment by eric-b** [comment]
I don't use Docker engine anymore, so I can't test it, but this should be as simple as this:

```
version: '3.1'
services:
  livebox-exporter:
    image: "eric1901/livebox-exporter"
    ports:
     - "9105:9105/tcp"
    environment:
     - "urls=http://*:9105"
     - "Livebox__Host=192.168.1.1"
     - "Livebox__Password=your-password"
```

I referred to this doc: https://docs.docker.com/compose/gettingstarted/

If you want to avoid to store the password in this file, you can refer to https://docs.docker.com/compose/how-tos/use-secrets/.
